<?php
namespace fge\apis\seeds;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class ligadosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('ligados')->insert([
            ["idcomponente"=>1,"idsistema"=>1,"idinvolucrado"=>1,"config"=>
            '{'.
                '"nombres":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"primerAp":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"segundoAp":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"rfc":{"rules":{'.
                    '"required":true,'.
                    '"rfchomo":true'.
                '}},'.
                '"curp":{"rules":{'.
                    '"required":true,'.
                    '"curp":true'.
                '}},'.
                '"fechaNacimiento":{"rules":{'.
                    '"required":true,'.
                    '"date":true'.
                '}}'.
            '}'],
            ["idcomponente"=>1,"idsistema"=>1,"idinvolucrado"=>2,"config"=>
            '{'.
                '"nombres":{"rules":{'.
                    '"required":true'.
                '}},'.
            '}'],        
            ["idcomponente"=>1,"idsistema"=>1,"idinvolucrado"=>3,"config"=>
            '{'.
                '"nombres":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"primerAp":{"rules":{'.
                    '"required":true'.
                '}},'.
            '}'],
            ["idcomponente"=>1,"idsistema"=>1,"idinvolucrado"=>4,"config"=>
            '{'.
                '"nombres":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"primerAp":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"segundoAp":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"rfc":{"rules":{'.
                    '"required":true,'.
                    '"rfchomo":true'.
                '}},'.
                '"curp":{"rules":{'.
                    '"required":true,'.
                    '"curp":true'.
                '}},'.
                '"fechaNacimiento":{"rules":{'.
                    '"required":true,'.
                    '"date":true'.
                '}}'.
            '}'],
            ["idcomponente"=>1,"idsistema"=>1,"idinvolucrado"=>5,"config"=>
            '{'.
                '"nombres":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"primerAp":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"segundoAp":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"rfc":{"rules":{'.
                    '"required":true,'.
                    '"rfchomo":true'.
                '}},'.
                '"curp":{"rules":{'.
                    '"required":true,'.
                    '"curp":true'.
                '}},'.
                '"fechaNacimiento":{"rules":{'.
                    '"required":true,'.
                    '"date":true'.
                '}}'.
                '"sexo":{"rules":{'.
                    '"required":true,'.
                '}}'.
            '}'],
            ["idcomponente"=>1,"idsistema"=>1,"idinvolucrado"=>6,"config"=>
            '{'.
                '"nombres":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"primerAp":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"segundoAp":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"rfc":{"rules":{'.
                    '"required":true,'.
                    '"rfchomo":true'.
                '}},'.
                '"curp":{"rules":{'.
                    '"required":true,'.
                    '"curp":true'.
                '}},'.
                '"fechaNacimiento":{"rules":{'.
                    '"required":true,'.
                    '"date":true'.
                '}}'.
            '}'],
            ["idcomponente"=>1,"idsistema"=>1,"idinvolucrado"=>7,"config"=>
            '{'.
                '"nombres":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"primerAp":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"segundoAp":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"rfc":{"rules":{'.
                    '"required":true,'.
                    '"rfchomo":true'.
                '}},'.
                '"curp":{"rules":{'.
                    '"required":true,'.
                    '"curp":true'.
                '}},'.
                '"fechaNacimiento":{"rules":{'.
                    '"required":true,'.
                    '"date":true'.
                '}}'.
            '}'],
            ["idcomponente"=>1,"idsistema"=>2,"idinvolucrado"=>8,"config"=>
            '{'.
                '"nombres":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"primerAp":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"segundoAp":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"rfc":{"rules":{'.
                    '"required":true,'.
                    '"rfchomo":true'.
                '}},'.
                '"curp":{"rules":{'.
                    '"required":true,'.
                    '"curp":true'.
                '}},'.
                '"fechaNacimiento":{"rules":{'.
                    '"required":true,'.
                    '"date":true'.
                '}}'.
            '}'],
            ["idcomponente"=>1,"idsistema"=>2,"idinvolucrado"=>9,"config"=>
            '{'.
                '"nombres":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"primerAp":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"segundoAp":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"rfc":{"rules":{'.
                    '"required":true,'.
                    '"rfchomo":true'.
                '}},'.
                '"curp":{"rules":{'.
                    '"required":true,'.
                    '"curp":true'.
                '}},'.
                '"fechaNacimiento":{"rules":{'.
                    '"required":true,'.
                    '"date":true'.
                '}}'.
            '}'],
            ["idcomponente"=>1,"idsistema"=>2,"idinvolucrado"=>10,"config"=>
            '{'.
                '"nombres":{"rules":{'.
                    '"required":true'.
                '}},'.
            '}'],
            ["idcomponente"=>1,"idsistema"=>2,"idinvolucrado"=>11,"config"=>
            '{'.
                '"nombres":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"primerAp":{"rules":{'.
                    '"required":true'.
                '}},'.
            '}'],
            ["idcomponente"=>1,"idsistema"=>2,"idinvolucrado"=>12,"config"=>
            '{'.
                '"nombres":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"primerAp":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"rfc":{"rules":{'.
                    '"required":true,'.
                    '"rfchomo":true'.
                '}},'.
                '"curp":{"rules":{'.
                    '"required":true,'.
                    '"curp":true'.
                '}},'.
                '"fechaNacimiento":{"rules":{'.
                    '"required":true,'.
                    '"date":true'.
                '}}'.
            '}'],
            ["idcomponente"=>1,"idsistema"=>2,"idinvolucrado"=>7,"config"=>
            '{'.
                '"nombres":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"primerAp":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"rfc":{"rules":{'.
                    '"required":true,'.
                    '"rfchomo":true'.
                '}},'.
                '"fechaNacimiento":{"rules":{'.
                    '"required":true,'.
                    '"date":true'.
                '}}'.
            '}'
            ],
            ["idcomponente"=>1,"idsistema"=>2,"idinvolucrado"=>5,"config"=>
            '{'.
                '"nombres":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"primerAp":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"rfc":{"rules":{'.
                    '"required":true,'.
                    '"rfchomo":true'.
                '}},'.
                '"curp":{"rules":{'.
                    '"required":true,'.
                    '"curp":true'.
                '}},'.
                '"fechaNacimiento":{"rules":{'.
                    '"required":true,'.
                    '"date":true'.
                '}}'.
            '}'],
        ]);
    }
}
