<?php
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class ligadosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //1,1,10 = comparecencia COMPLETO
        //1,1,11 = conocido PARCIAL
        //1,1,12 = QRR NULL
        DB::table('ligados')->insert([
            //COMPARECENCIA
            ["idcomponente"=>1,"idsistema"=>1,"idinvolucrado"=>10,"config"=>
            '{'.
                '"nombres":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"primerAp":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"segundoAp":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"rfc":{"rules":{'.
                    '"required":true,'.
                    '"rfc":true'.
                '}},'.
                '"curp":{"rules":{'.
                    '"required":true,'.
                    '"curp":true'.
                '}},'.
                '"fechaNacimiento":{"rules":{'.
                    '"required":true,'.
                    '"date":true'.
                '},"default":"1990-01-01"},'.
                '"edad":{"rules":{'.
                    '"required":false,'.
                    '"number":true'.
                '}},'.
                '"idNacionalidad":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"idEdoOrigen":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"idMunicipioOrigen":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"sexo":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"idEtnia":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"idLengua":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"motivoEstancia":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"idOcupacion":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"idEstadoCivil":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"idReligion":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"idEscolaridad":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"docIdentificacion":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"numDocIdentificacion":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"alias":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"idInterprete":{"rules":{'.
                    '"required":false'.
                '}}'.
            '}'],
            //CONOCIDO
            ["idcomponente"=>1,"idsistema"=>1,"idinvolucrado"=>11,"config"=>
            '{'.
                '"nombres":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"primerAp":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"segundoAp":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"rfc":{"rules":{'.
                    '"required":false,'.
                    '"rfc":true'.
                '}},'.
                '"curp":{"rules":{'.
                    '"required":false,'.
                    '"curp":true'.
                '}},'.
                '"fechaNacimiento":{"rules":{'.
                    '"required":false,'.
                    '"date":true'.
                '},"default":"1990-01-01"},'.
                '"edad":{"rules":{'.
                    '"required":false,'.
                    '"number":true'.
                '}},'.
                '"idNacionalidad":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"idEdoOrigen":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"idMunicipioOrigen":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"sexo":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"idEtnia":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"idLengua":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"motivoEstancia":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"idOcupacion":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"idEstadoCivil":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"idReligion":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"idEscolaridad":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"docIdentificacion":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"numDocIdentificacion":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"alias":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"idInterprete":{"rules":{'.
                    '"required":false'.
                '}}'.
            '}'],
            //QRR
            ["idcomponente"=>1,"idsistema"=>1,"idinvolucrado"=>12,"config"=>
            '{'.
                '"nombres":{"default":"QUIEN RESULTE RESPONSABLE","rules":{'.
                    '"required":false'.
                '}},'.
                '"primerAp":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"segundoAp":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"rfc":{"rules":{'.
                    '"required":false,'.
                    '"rfc":true'.
                '}},'.
                '"curp":{"rules":{'.
                    '"required":false,'.
                    '"curp":true'.
                '}},'.
                '"fechaNacimiento":{"rules":{'.
                    '"required":false,'.
                    '"date":true'.
                '},"default":"1990-01-01"},'.
                '"edad":{"rules":{'.
                    '"required":false,'.
                    '"number":true'.
                '}},'.
                '"idNacionalidad":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"idEdoOrigen":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"idMunicipioOrigen":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"sexo":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"idEtnia":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"idLengua":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"motivoEstancia":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"idOcupacion":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"idEstadoCivil":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"idReligion":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"idEscolaridad":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"docIdentificacion":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"numDocIdentificacion":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"alias":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"idInterprete":{"rules":{'.
                    '"required":false'.
                '}}'.
            '}'],
            //COMPARECENCIA
            ["idcomponente"=>1,"idsistema"=>2,"idinvolucrado"=>1,"config"=>
            '{'.
                '"nombres":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"primerAp":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"segundoAp":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"rfc":{"rules":{'.
                    '"required":true,'.
                    '"rfc":true'.
                '}},'.
                '"curp":{"rules":{'.
                    '"required":true,'.
                    '"curp":true'.
                '}},'.
                '"fechaNacimiento":{"rules":{'.
                    '"required":true,'.
                    '"date":true'.
                '},"default":"1990-01-01"},'.
                '"edad":{"rules":{'.
                    '"required":false,'.
                    '"number":true'.
                '}},'.
                '"idNacionalidad":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"idEdoOrigen":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"idMunicipioOrigen":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"sexo":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"idEtnia":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"idLengua":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"motivoEstancia":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"idOcupacion":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"idEstadoCivil":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"idReligion":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"idEscolaridad":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"docIdentificacion":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"numDocIdentificacion":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"alias":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"idInterprete":{"rules":{'.
                    '"required":false'.
                '}}'.
            '}'],
            //CONOCIDO
            ["idcomponente"=>1,"idsistema"=>2,"idinvolucrado"=>2,"config"=>
            '{'.
                '"nombres":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"primerAp":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"segundoAp":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"rfc":{"rules":{'.
                    '"required":false,'.
                    '"rfc":true'.
                '}},'.
                '"curp":{"rules":{'.
                    '"required":false,'.
                    '"curp":true'.
                '}},'.
                '"fechaNacimiento":{"rules":{'.
                    '"required":false,'.
                    '"date":true'.
                '},"default":"1990-01-01"},'.
                '"edad":{"rules":{'.
                    '"required":false,'.
                    '"number":true'.
                '}},'.
                '"idNacionalidad":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"idEdoOrigen":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"idMunicipioOrigen":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"sexo":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"idEtnia":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"idLengua":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"motivoEstancia":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"idOcupacion":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"idEstadoCivil":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"idReligion":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"idEscolaridad":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"docIdentificacion":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"numDocIdentificacion":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"alias":{"rules":{'.
                    '"required":true'.
                '}},'.
                '"idInterprete":{"rules":{'.
                    '"required":false'.
                '}}'.
            '}'],
            //QRR
            ["idcomponente"=>1,"idsistema"=>2,"idinvolucrado"=>3,"config"=>
            '{'.
                '"nombres":{"default":"QUIEN RESULTE RESPONSABLE","rules":{'.
                    '"required":false'.
                '}},'.
                '"primerAp":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"segundoAp":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"rfc":{"rules":{'.
                    '"required":false,'.
                    '"rfc":true'.
                '}},'.
                '"curp":{"rules":{'.
                    '"required":false,'.
                    '"curp":true'.
                '}},'.
                '"fechaNacimiento":{"rules":{'.
                    '"required":false,'.
                    '"date":true'.
                '},"default":"1990-01-01"},'.
                '"edad":{"rules":{'.
                    '"required":false,'.
                    '"number":true'.
                '}},'.
                '"idNacionalidad":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"idEdoOrigen":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"idMunicipioOrigen":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"sexo":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"idEtnia":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"idLengua":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"motivoEstancia":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"idOcupacion":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"idEstadoCivil":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"idReligion":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"idEscolaridad":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"docIdentificacion":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"numDocIdentificacion":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"alias":{"rules":{'.
                    '"required":false'.
                '}},'.
                '"idInterprete":{"rules":{'.
                    '"required":false'.
                '}}'.
            '}'],
        ]);
    }
}
