<?php
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class validacionesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('validaciones')->insert([
            [
                "sistema"=>"uat",
                "tipo"=>"autoridad",
                "validaciones"=>'{
                    "nombres": "required",
                    "primerAp": "required",
                    "segundoAp": "",
                    "telefono":"numeric",
                    "fechaNacimiento": "required",
                    "idEstadoOrigen": "required",
                    "idMunicipioOrigen": "required",
                    "sexo": "required",
                    "curp": "required|length:18",
                    "rfc": "required|length:10",
                    "homo": "required|length:3",
                    "idNacionalidad": "",
                    "idEtnia": "",
                    "idLengua": "",
                    "idOcupacion": "",
                    "idEstadoCivil": "",
                    "idReligion": "",
                    "idEscolaridad": "",
                    "docIdentificacion": "required",
                    "numDocIdentificacion": "required",
                    "edad": "oculto",
                    "alias": "oculto",
                    "idInterprete": "oculto",
                    "motivoEstancia": "oculto"
               }'
            ],
            [
                "sistema"=>"uat",
                "tipo"=>"abogado",
                "validaciones"=>'{
                    "nombres": "required",
                    "primerAp": "required",
                    "segundoAp": "",
                    "telefono":"numeric",
                    "fechaNacimiento": "required",
                    "idEstadoOrigen": "required",
                    "idMunicipioOrigen": "required",
                    "sexo": "required",
                    "curp": "required|length:18",
                    "rfc": "required|length:10",
                    "homo": "required|length:3",
                    "idNacionalidad": "oculto",
                    "idEtnia": "oculto",
                    "idLengua": "oculto",
                    "idOcupacion": "oculto",
                    "idEstadoCivil": "",
                    "idReligion": "oculto",
                    "idEscolaridad": "oculto",
                    "docIdentificacion": "oculto",
                    "numDocIdentificacion": "oculto",
                    "edad": "oculto",
                    "alias": "oculto",
                    "idInterprete": "oculto",
                    "motivoEstancia": "oculto"
               }'
            ],
            [
                "sistema"=>"uat",
                "tipo"=>"conocido",
                "validaciones"=>'{
                    "nombres": "",
                    "primerAp": "",
                    "segundoAp": "",
                    "telefono":"oculto",
                    "fechaNacimiento": "oculto",
                    "idEstadoOrigen": "oculto",
                    "idMunicipioOrigen": "oculto",
                    "sexo": "oculto",
                    "curp": "oculto",
                    "rfc": "oculto",
                    "homo": "oculto",
                    "idNacionalidad": "oculto",
                    "idEtnia": "oculto",
                    "idLengua": "oculto",
                    "idOcupacion": "oculto",
                    "idEstadoCivil": "oculto",
                    "idReligion": "oculto",
                    "idEscolaridad": "oculto",
                    "docIdentificacion": "oculto",
                    "numDocIdentificacion": "oculto",
                    "edad": "oculto",
                    "alias": "",
                    "idInterprete": "oculto",
                    "motivoEstancia": "oculto"
               }'
            ],
            [
                "sistema"=>"uat",
                "tipo"=>"denunciado",
                "validaciones"=>'{
                    "nombres": "required",
                    "primerAp": "required",
                    "segundoAp": "",
                    "telefono":"numeric",
                    "fechaNacimiento": "required",
                    "idEstadoOrigen": "required",
                    "idMunicipioOrigen": "required",
                    "sexo": "required",
                    "curp": "required|length:18",
                    "rfc": "required|length:10",
                    "homo": "required|length:3",
                    "idNacionalidad": "",
                    "idEtnia": "",
                    "idLengua": "",
                    "idOcupacion": "",
                    "idEstadoCivil": "",
                    "idReligion": "",
                    "idEscolaridad": "",
                    "docIdentificacion": "",
                    "numDocIdentificacion": "",
                    "edad": "oculto",
                    "alias": "oculto",
                    "idInterprete": "oculto",
                    "motivoEstancia": "oculto"
               }'
            ],
            [
                "sistema"=>"uat",
                "tipo"=>"denunciante",
                "validaciones"=>'{
                    "nombres": "required",
                    "primerAp": "required",
                    "segundoAp": "",
                    "telefono":"numeric",
                    "fechaNacimiento": "required",
                    "idEstadoOrigen": "required",
                    "idMunicipioOrigen": "required",
                    "sexo": "required",
                    "curp": "required|length:18",
                    "rfc": "required|length:10",
                    "homo": "required|length:3",
                    "idNacionalidad": "",
                    "idEtnia": "",
                    "idLengua": "",
                    "idOcupacion": "",
                    "idEstadoCivil": "",
                    "idReligion": "",
                    "idEscolaridad": "",
                    "docIdentificacion": "required",
                    "numDocIdentificacion": "required",
                    "edad": "oculto",
                    "alias": "oculto",
                    "idInterprete": "oculto",
                    "motivoEstancia": "oculto"
               }'
            ],
            [
                "sistema"=>"uat",
                "tipo"=>"qrr",
                "validaciones"=>'{
                    "nombres": "oculto",
                    "primerAp": "oculto",
                    "segundoAp": "oculto",
                    "telefono":"oculto",
                    "fechaNacimiento": "oculto",
                    "idEstadoOrigen": "oculto",
                    "idMunicipioOrigen": "oculto",
                    "sexo": "oculto",
                    "curp": "oculto",
                    "rfc": "oculto",
                    "homo": "oculto",
                    "idNacionalidad": "oculto",
                    "idEtnia": "oculto",
                    "idLengua": "oculto",
                    "idOcupacion": "oculto",
                    "idEstadoCivil": "oculto",
                    "idReligion": "oculto",
                    "idEscolaridad": "oculto",
                    "docIdentificacion": "oculto",
                    "numDocIdentificacion": "oculto",
                    "edad": "oculto",
                    "alias": "oculto",
                    "idInterprete": "oculto",
                    "motivoEstancia": "oculto"
               }'
            ],
            [
                "sistema"=>"uat",
                "tipo"=>"actashechos",
                "validaciones"=>'{
                    "nombres": "required",
                    "primerAp": "required",
                    "segundoAp": "",
                    "telefono":"required|numeric",
                    "fechaNacimiento": "required",
                    "idEstadoOrigen": "required",
                    "idMunicipioOrigen": "required",
                    "sexo": "required",
                    "curp": "required|length:18",
                    "rfc": "required|length:10",
                    "homo": "required|length:3",
                    "idNacionalidad": "required",
                    "idEtnia": "oculto",
                    "idLengua": "oculto",
                    "idOcupacion": "required",
                    "idEstadoCivil": "required",
                    "idReligion": "oculto",
                    "idEscolaridad": "required",
                    "docIdentificacion": "required",
                    "numDocIdentificacion": "required",
                    "edad": "oculto",
                    "alias": "oculto",
                    "idInterprete": "oculto",
                    "motivoEstancia": "oculto"
               }'
            ],
            [
                "sistema"=>"uat",
                "tipo"=>"actascircunstanciadas",
                "validaciones"=>'{
                    "nombres": "required",
                    "primerAp": "required",
                    "segundoAp": "",
                    "telefono":"required|numeric",
                    "fechaNacimiento": "required",
                    "idEstadoOrigen": "required",
                    "idMunicipioOrigen": "required",
                    "sexo": "required",
                    "curp": "required|length:18",
                    "rfc": "required|length:10",
                    "homo": "required|length:3",
                    "idNacionalidad": "required",
                    "idEtnia": "oculto",
                    "idLengua": "oculto",
                    "idOcupacion": "required",
                    "idEstadoCivil": "required",
                    "idReligion": "oculto",
                    "idEscolaridad": "required",
                    "docIdentificacion": "required",
                    "numDocIdentificacion": "required",
                    "edad": "oculto",
                    "alias": "oculto",
                    "idInterprete": "oculto",
                    "motivoEstancia": "oculto"
               }'
            ]
        ]);
    }
}
